export const MAX_API_JSON_RESPONSE_BYTES = 2 * 1024 * 1024;
export const READING_DETAIL_JSON_LIMIT_BYTES =
  MAX_API_JSON_RESPONSE_BYTES;
export const READING_JSON_BODY_LIMIT_BYTES = 2 * 1024 * 1024;
export const READING_BODY_JSON_LIMIT_BYTES = 1_900_000;
